package com.dcoj.dao;

import com.dcoj.entity.ExaminationEntity;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

/**
 *  试卷持久层接口
 */
@Repository
public interface ExaminationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer examId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination
     *
     * @mbg.generated
     */
    int insert(ExaminationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination
     *
     * @mbg.generated
     */
    int insertSelective(ExaminationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination
     *
     * @mbg.generated
     */
    ExaminationEntity selectByPrimaryKey(@Param("examId") Integer examId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExaminationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExaminationEntity record);

    /**
     *  查询所有试卷
     * @return
     */
    List<Map<String, Object>> listAll();
    /**
     *  查询所有试卷
     * @return
     */
    List<Map<String, Object>> listAllWithQuery(@Param("query") String query);

}