package com.dcoj.entity;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.annotation.JSONField;
import lombok.Data;

import java.util.Date;
import java.util.List;
import java.util.Map;

/**
 *  试卷实体类
 */
@Data
public class ExaminationEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.exam_id
     *
     * @mbg.generated
     */
    private Integer examId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.time_limited
     *
     * @mbg.generated
     */
    private Integer timeLimited;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.exam_template_id
     *
     * @mbg.generated
     */
    private Integer examTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.queryable_time
     *
     * @mbg.generated
     */
    private Date queryableTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.deadline
     *
     * @mbg.generated
     */
    private Date deadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.author
     *
     * @mbg.generated
     */
    private String author;

    private List<?> program_problem;

    private List<?> single_problem;

    private JSONArray single_id;

    private JSONArray program_id;

}