spring:
  data:
    mongodb:
      uri: mongodb://localhost/dcoj_api
  mail:
    host: smtp.zoho.com
    username: dcoj@email.ylpriv.com
    password: Aa@13524
    default-encoding: utf-8
    port: 587
    protocol: smtp
    properties:
      "mail.smtp.starttls.enable": "true"
mail:
  fromMail:
     addr: dcoj@email.ylpriv.com
