
spring:
  datasource:
    # 数据库访问配置, 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dcoj?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://localhost/dcoj_api

  mail:
    host: smtp.zoho.com
    username: dcoj@email.ylpriv.com
    password: Aa@13524
    default-encoding: utf-8
    port: 587
    protocol: smtp
    properties:
      "mail.smtp.starttls.enable": "true"
mail:
  fromMail:
     addr: dcoj@email.ylpriv.com

mybatis:
  mapperLocations: classpath:mapping/*.xml
  typeAliasesPackage: com.dcoj.entity
  type-handlers-package: com.dcoj.handler
  # 打印Mybatis日志
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


mapper:
  mappers: com.dcoj.dao
  not-empty: false
  identity: MYSQL
